language: minimal
branches:
  only:
    - master # build master branch only
script:
  - ./blocklist-build.sh
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: blocklist.gz
  skip_cleanup: true
  overwrite: true
